version: '3.8'

services:
  profit-bot:
    build: .
    container_name: profit-bot
    restart: unless-stopped
    volumes:
      - ./:/app
      - type: bind
        source: G:/
        target: /data/history_files
        read_only: true
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - LOG_FOLDER=/data/history_files