version: '3.8'

services:
  profit-t-bot:
    build: .
    container_name: profit-t-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: //pilot.ru/Soft/Distr/CASH66.BET
        target: /app/logs
        read_only: true
        bind:
          propagation: rshared
